name: Release eslint-config
concurrency:
  group: publish-${{ github.github.base_ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: "Choose the release type"
        options:
          - auto
          - patch
          - minor
          - major
        default: auto
      beta:
        type: boolean
        description: Prerelease
        default: false
      dry:
        type: boolean
        description: Dry run release
        default: false

jobs:
  publish:
    if: github.repository == 'novemberfiveco/eslint-config' && github.ref == 'refs/heads/master'
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          registry-url: https://registry.npmjs.org/
          cache: "npm"

      - name: Git Config
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: NPM Credentials
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm run release -- --ci --verbose $TYPE_ARG $BETA_ARG $DRY_ARG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE_ARG: ${{ fromJSON('{"auto":"", "patch":"--patch", "minor":"--minor", "major":"--major"}')[github.event.inputs.type] }}
          BETA_ARG: ${{ github.event.inputs.beta == 'true' && '--preRelease=beta' || '' }}
          DRY_ARG: ${{ github.event.inputs.dry == 'true' && '--dry-run' || '' }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
